import type { CategoryContent, IndustryContent, ProductContent } from './schema';

/** Origin language — the one content rule enforced mechanically. */
export const ORIGIN_PATTERN = /manufactur|our plant|our factory|we produce|our production|produced to our/i;
export const CONFIRM_PATTERN = /\[CONFIRM(?::\s*([^\]]+))?\]/g;

export interface ValidationInput {
  products: ProductContent[];
  categories: CategoryContent[];
  industries: IndustryContent[];
  /** Other copy objects (home, company, site) scanned for origin language and [CONFIRM] markers. */
  copy: Record<string, unknown>;
  /** Resolves whether an image slot has a real asset behind it. */
  imageExists: (src: string) => boolean;
}

export interface ValidationResult {
  errors: string[];
  confirms: { where: string; text: string }[];
  missingImages: { product: string; slot: string; src: string; shot: string }[];
}

/** Walk every string in a value, reporting a dotted path. */
function walkStrings(value: unknown, path: string, visit: (s: string, path: string) => void) {
  if (typeof value === 'string') visit(value, path);
  else if (Array.isArray(value)) value.forEach((v, i) => walkStrings(v, `${path}[${i}]`, visit));
  else if (value && typeof value === 'object')
    for (const [k, v] of Object.entries(value)) walkStrings(v, path ? `${path}.${k}` : k, visit);
}

export function validateContent(input: ValidationInput): ValidationResult {
  const { products, categories, industries, copy, imageExists } = input;
  const errors: string[] = [];
  const confirms: ValidationResult['confirms'] = [];
  const missingImages: ValidationResult['missingImages'] = [];

  const productSlugs = new Set(products.map((p) => p.slug));
  const categorySlugs = new Set(categories.map((c) => c.slug));
  const industrySlugs = new Set(industries.map((i) => i.slug));

  if (productSlugs.size !== products.length) errors.push('Duplicate product slug in content/products');

  const scan = (root: unknown, label: string) =>
    walkStrings(root, '', (s, path) => {
      if (ORIGIN_PATTERN.test(s)) errors.push(`${label}${path ? ` → ${path}` : ''}: origin language "${s.match(ORIGIN_PATTERN)?.[0]}" in "${s.slice(0, 90)}…"`);
      for (const m of s.matchAll(CONFIRM_PATTERN)) confirms.push({ where: label, text: m[1]?.trim() ?? '(unspecified)' });
    });

  for (const p of products) {
    const at = `products/${p.slug}`;
    if (!/^[a-z0-9-]+$/.test(p.slug)) errors.push(`${at}: slug must be kebab-case`);
    if (!categorySlugs.has(p.category)) errors.push(`${at}: category "${p.category}" does not resolve`);
    for (const r of p.related) {
      if (!productSlugs.has(r)) errors.push(`${at}: related slug "${r}" does not resolve`);
      if (r === p.slug) errors.push(`${at}: related lists itself`);
    }
    for (const i of p.industries) if (!industrySlugs.has(i)) errors.push(`${at}: industry slug "${i}" does not resolve`);
    if (p.faqs.length === 0) errors.push(`${at}: faqs is empty`);
    for (const img of p.images) {
      if (!img.shot?.trim()) errors.push(`${at}: image slot "${img.slot}" has no shot description`);
      if (!img.alt?.trim()) errors.push(`${at}: image slot "${img.slot}" has no alt text`);
      if (!imageExists(img.src)) missingImages.push({ product: p.slug, slot: img.slot, src: img.src, shot: img.shot });
    }
    if (!p.images.some((i) => i.slot === 'hero')) errors.push(`${at}: no hero image slot`);
    scan(p, at);
  }

  categories.forEach((c) => scan(c, `categories/${c.slug}`));
  industries.forEach((i) => {
    scan(i, `industries/${i.slug}`);
    if (!products.some((p) => p.industries.includes(i.slug))) errors.push(`industries/${i.slug}: no products tagged`);
  });
  for (const [name, value] of Object.entries(copy)) scan(value, name);

  return { errors, confirms, missingImages };
}

export function renderOutstanding(result: ValidationResult, notes: string[]): string {
  const byWhere = new Map<string, string[]>();
  for (const c of result.confirms) byWhere.set(c.where, [...(byWhere.get(c.where) ?? []), c.text]);
  const byProduct = new Map<string, ValidationResult['missingImages']>();
  for (const m of result.missingImages) byProduct.set(m.product, [...(byProduct.get(m.product) ?? []), m]);

  const lines: string[] = [
    '# Outstanding items',
    '',
    '_Generated by `npm run validate` — do not edit by hand._',
    '',
    `**${result.confirms.length} [CONFIRM] markers · ${result.missingImages.length} missing images**`,
    '',
    '## [CONFIRM] markers',
    '',
    'Each commits Arivo to a fact and needs sign-off before publication. They render visibly on the site until resolved.',
    '',
  ];
  for (const [where, items] of byWhere) {
    lines.push(`### ${where}`, '');
    // de-duplicate repeated markers within one source
    for (const t of [...new Set(items)]) lines.push(`- [ ] ${t}`);
    lines.push('');
  }
  lines.push('## Missing images', '', 'Placeholders render at the final aspect ratio, so layout will not shift when these land.', '');
  for (const [product, items] of byProduct) {
    lines.push(`### ${product}`, '');
    for (const m of items) lines.push(`- [ ] **${m.slot}** \`public${m.src.startsWith('/') ? m.src : `/${m.src}`}\` — ${m.shot}`);
    lines.push('');
  }
  if (notes.length) {
    lines.push('## Build notes', '');
    for (const n of notes) lines.push(`- ${n}`);
    lines.push('');
  }
  return lines.join('\n');
}
